services:
  - type: web
    name: astroconnect-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
